<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.de-gupta</groupId>
    <artifactId>aegis</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <name>aegis</name>
    <description>A validation library for java using the specification pattern mainly</description>
    <url>https://github.com/de-gupta/aegis.git</url>

    <properties>
        <maven.compiler.source>24</maven.compiler.source>
        <maven.compiler.target>24</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <aletheia.version>0.0.7</aletheia.version>
        <commons.utility.version>0.0.6-SNAPSHOT</commons.utility.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.github.de-gupta</groupId>
            <artifactId>aletheia</artifactId>
            <version>${aletheia.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.de-gupta</groupId>
            <artifactId>commons-utility</artifactId>
            <version>${commons.utility.version}</version>
        </dependency>
    </dependencies>

</project>